// Main types export file - using explicit exports to avoid conflicts
export type {
  // Components
  BaseComponentProps,
  AnimatedComponentProps,
  SectionProps,
  ClipPathTitleProps,
  VideoPinSectionProps,
  HeroSectionProps,
  MessageSectionProps,
  FlavorSectionProps,
  FlavorItem,
  FlavorSliderProps,
  FlavorTitleProps,
  NutritionSectionProps,
  NutrientItem,
  BenefitSectionProps,
  BenefitItem,
  TestimonialSectionProps,
  TestimonialCard,
  FooterSectionProps,
  SocialLink,
  ContactInfo,
  NavBarProps,
  MenuItem,
  LoadingSpinnerProps,
  ErrorNotificationProps,
  NoScriptFallbackProps,
  SafeSectionProps,
  VideoLoaderProps,
  ImageLoaderProps,
  GSAPProviderProps,
  ErrorProviderProps,
  FormProps,
  ModalProps,
  ButtonProps,
} from "./components";

export type {
  // GSAP
  GSAPTimelineConfig,
  ScrollTriggerConfig,
  ScrollSmootherConfig,
  SplitTextConfig,
  AnimationConfig,
  GSAPTweenVars,
  GSAPContextReturn,
  GSAPPlugins,
  AnimationState,
  AnimationControls,
  GSAPPerformanceMetrics,
  GSAPAppConfig,
} from "./gsap";

export type {
  // Media
  ImageOptimizationConfig,
  VideoOptimizationConfig,
  MediaLoadingStrategy,
  DeviceCapabilities,
  ImageDimensions,
  VideoConfig,
  MediaLoaderState,
  MediaCacheEntry,
  MediaCacheConfig,
  ResponsiveBreakpoints,
  MediaOptimizationResult,
  OptimizedImageProps,
  OptimizedVideoProps,
  MediaLoaderProps,
  MediaPerformanceMetrics,
  MediaLoadingEvent,
} from "./media";

export * from "./constants";

export type {
  // Utils
  Nullable,
  Optional,
  Maybe,
  VoidFunction,
  AsyncVoidFunction,
  EventHandler,
  AsyncEventHandler,
  DebounceOptions,
  ThrottleOptions,
  DebouncedFunction,
  ThrottledFunction,
  PerformanceMetrics,
  PerformanceObserverConfig,
  ErrorInfo,
  ErrorReport as UtilsErrorReport,
  ErrorHandlerConfig as UtilsErrorHandlerConfig,
  ValidationRule,
  ValidationSchema,
  ValidationResult,
  StorageOptions,
  StorageItem,
  URLParams,
  RouteConfig,
  APIResponse,
  APIError as UtilsAPIError,
  RequestConfig,
  DateRange,
  TimeZoneInfo,
  DateFormatOptions,
  RGBColor,
  HSLColor,
  ColorPalette,
  AnimationKeyframe,
  AnimationSequence,
  Point,
  Size,
  Rectangle,
  Circle,
  DeviceInfo,
  AccessibilityConfig,
  ARIAAttributes,
  LocaleConfig,
  TranslationKey,
  TestConfig,
  MockFunction,
  ConfigProvider,
} from "./utils";

export type {
  // Hooks
  BaseHookReturn,
  UseGSAPOptions,
  UseGSAPReturn,
  UseScrollTriggerOptions,
  UseScrollTriggerReturn,
  UseScrollSmootherOptions,
  UseScrollSmootherReturn,
  UseAnimationOptions,
  UseAnimationReturn,
  UseMediaOptimizationReturn,
  UseImageLoaderOptions,
  UseImageLoaderReturn,
  UseVideoLoaderOptions,
  UseVideoLoaderReturn,
  UseMediaQueryOptions,
  UseMediaQueryReturn,
  UseResponsiveReturn,
  UseViewportOptions,
  UseViewportReturn,
  UsePerformanceMonitoringOptions,
  UsePerformanceMonitoringReturn,
  UseIntersectionObserverOptions,
  UseIntersectionObserverReturn,
  UseErrorHandlingOptions,
  UseErrorHandlingReturn,
  UseErrorBoundaryReturn,
  UseLocalStorageOptions,
  UseLocalStorageReturn,
  UseSessionStorageReturn,
  UseDebounceOptions,
  UseDebounceReturn,
  UseThrottleOptions,
  UseThrottleReturn,
  UseFormOptions,
  UseFormReturn,
  UseAPIOptions,
  UseAPIReturn,
  UseDeviceDetectionReturn,
  UseNetworkStatusReturn,
  UseBatteryStatusReturn,
  UseScrollAnimationOptions,
  UseScrollAnimationReturn,
  UseParallaxOptions,
  UseParallaxReturn,
  UseAccessibilityReturn,
  UseFocusManagementOptions,
  UseFocusManagementReturn,
  UseClipboardReturn,
  UseToggleReturn,
  UseCounterOptions,
  UseCounterReturn,
} from "./hooks";

export type {
  // Errors
  BaseError,
  GSAPError,
  MediaError,
  APIError,
  ValidationError,
  PerformanceError,
  NetworkError,
  ComponentError,
  ErrorSeverity,
  ErrorCategory,
  ErrorContext,
  ErrorReport,
  ErrorBreadcrumb,
  ErrorBoundaryState,
  ErrorBoundaryProps,
  ErrorFallbackProps,
  ErrorHandlerConfig,
  ErrorRecoveryStrategy,
  ErrorNotificationConfig,
  ErrorAnalytics,
  UseErrorMonitoringOptions,
  UseErrorMonitoringReturn,
  RetryConfig,
  RecoveryResult,
  GlobalErrorHandler,
  ErrorTestUtils,
  ErrorMetrics,
} from "./errors";
